library(dplyr)
library(ggplot2)
png(filename="plot6.png", height=480, width=600,bg="white")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
filteredSCC <- SCC %.% filter(grepl(".*On-Road.*",EI.Sector)) 
final <- NEI %.% filter(fips == "24510" | fips == "06037") %.% filter(SCC %in% filteredSCC$SCC) %.% group_by(fips,year) %.% summarise(total= sum(Emissions))
qplot(final$year, final$total, data=final, color=fips) + geom_smooth(method=lm)
dev.off()