library(dplyr)
library(ggplot2)
png(filename="plot5.png", height=480, width=600,bg="white")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
filteredSCC <- SCC %.% filter(grepl(".*On-Road.*",EI.Sector)) 
final <- NEI %.% filter(SCC %in% filteredSCC$SCC) %.% group_by(year) %.% summarise(total= sum(Emissions))
plot(final$year, final$total,type="o")
dev.off()